server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Spring Boot Restful Web Services
    description: Spring Boot Restful Web Services Demo
    version: 1.0.0